spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/airline_reservation
    username: postgres
    password: 1
  jpa:
    database: postgresql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        hbm2ddl:auto: none
  flyway:
    locations: classpath:db/migration
    enabled: true
    clean-disabled: true
    baseline-on-migrate: true
    schemas: public
    default-schema: public
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/airline_reservation
    user: postgres
    password: 1

logging:
  level:
    org:
      springframework: info
      hibernate: info
      flywaydb: info
    com:
      dmytrobozhor.airlinereservationservice: debug

server:
  port: 8080

springdoc:
  swagger-ui:
    url: /api-docs.yaml